/// TransformationEngineTests.swift
/// Tests for the HL7 Transformation Engine
///
/// Comprehensive test suite for transformation framework, including
/// core protocols, configuration, metrics, and error handling.

import XCTest
@testable import HL7v3Kit
@testable import HL7Core

#if canImport(HL7v2Kit)
import HL7v2Kit
#endif

final class TransformationEngineTests: XCTestCase {
    
    // MARK: - Configuration Tests
    
    func testDefaultConfiguration() {
        let config = TransformationConfiguration.default
        
        XCTAssertEqual(config.validationMode, .strict)
        XCTAssertEqual(config.dataLossMode, .warn)
        XCTAssertTrue(config.trackMetrics)
        XCTAssertEqual(config.timeout, 30.0)
        XCTAssertTrue(config.customRules.isEmpty)
    }
    
    func testLenientConfiguration() {
        let config = TransformationConfiguration.lenient
        
        XCTAssertEqual(config.validationMode, .lenient)
        XCTAssertEqual(config.dataLossMode, .ignore)
        XCTAssertFalse(config.trackMetrics)
        XCTAssertEqual(config.timeout, 60.0)
    }
    
    func testCustomConfiguration() {
        let rule = TransformationRule(
            id: "test-1",
            description: "Test rule",
            sourcePath: "PID-5",
            targetPath: "patient.name",
            required: true
        )
        
        let config = TransformationConfiguration(
            validationMode: .lenient,
            dataLossMode: .warn,
            trackMetrics: true,
            timeout: 45.0,
            customRules: [rule]
        )
        
        XCTAssertEqual(config.validationMode, .lenient)
        XCTAssertEqual(config.dataLossMode, .warn)
        XCTAssertTrue(config.trackMetrics)
        XCTAssertEqual(config.timeout, 45.0)
        XCTAssertEqual(config.customRules.count, 1)
        XCTAssertEqual(config.customRules[0].id, "test-1")
    }
    
    // MARK: - Context Tests
    
    func testTransformationContext() {
        let config = TransformationConfiguration.default
        let metadata = ["facility": "TEST_HOSPITAL", "department": "ER"]
        let operationId = "test-op-123"
        
        let context = TransformationContext(
            configuration: config,
            metadata: metadata,
            operationId: operationId
        )
        
        XCTAssertEqual(context.configuration.validationMode, .strict)
        XCTAssertEqual(context.metadata["facility"], "TEST_HOSPITAL")
        XCTAssertEqual(context.metadata["department"], "ER")
        XCTAssertEqual(context.operationId, operationId)
        XCTAssertNotNil(context.timestamp)
    }
    
    func testContextWithAutoGeneratedOperationId() {
        let context = TransformationContext()
        
        XCTAssertFalse(context.operationId.isEmpty)
        // Should be a valid UUID format
        XCTAssertNotNil(UUID(uuidString: context.operationId))
    }
    
    // MARK: - Rule Tests
    
    func testTransformationRule() {
        let rule = TransformationRule(
            id: "rule-1",
            description: "Map patient name",
            sourcePath: "PID-5",
            targetPath: "recordTarget.patient.name",
            transform: { $0.uppercased() },
            required: true
        )
        
        XCTAssertEqual(rule.id, "rule-1")
        XCTAssertEqual(rule.description, "Map patient name")
        XCTAssertEqual(rule.sourcePath, "PID-5")
        XCTAssertEqual(rule.targetPath, "recordTarget.patient.name")
        XCTAssertTrue(rule.required)
        XCTAssertNotNil(rule.transform)
        
        let result = rule.transform?("john doe")
        XCTAssertEqual(result, "JOHN DOE")
    }
    
    func testOptionalTransformationRule() {
        let rule = TransformationRule(
            id: "rule-2",
            description: "Map phone number",
            sourcePath: "PID-13",
            targetPath: "patient.telecom",
            transform: nil,
            required: false
        )
        
        XCTAssertFalse(rule.required)
        XCTAssertNil(rule.transform)
    }
    
    // MARK: - Error Tests
    
    func testTransformationError() {
        let error = TransformationError(
            code: "MISSING_FIELD",
            message: "Required field not found",
            severity: .error,
            location: "PID-5"
        )
        
        XCTAssertEqual(error.code, "MISSING_FIELD")
        XCTAssertEqual(error.message, "Required field not found")
        XCTAssertEqual(error.severity, .error)
        XCTAssertEqual(error.location, "PID-5")
    }
    
    func testTransformationErrorEquality() {
        let error1 = TransformationError(
            code: "ERROR_1",
            message: "Message 1",
            severity: .error
        )
        
        let error2 = TransformationError(
            code: "ERROR_1",
            message: "Message 1",
            severity: .error
        )
        
        let error3 = TransformationError(
            code: "ERROR_2",
            message: "Message 2",
            severity: .warning
        )
        
        XCTAssertEqual(error1, error2)
        XCTAssertNotEqual(error1, error3)
    }
    
    // MARK: - Result Tests
    
    func testSuccessfulResult() {
        let result = TransformationResult<String>.success(
            "Transformed data",
            warnings: ["Minor issue"],
            info: ["Processed successfully"],
            metrics: TransformationMetrics(
                duration: 0.5,
                fieldsMapped: 10,
                fieldsUnmapped: 2,
                dataLossCount: 0
            )
        )
        
        XCTAssertTrue(result.success)
        XCTAssertEqual(result.target, "Transformed data")
        XCTAssertTrue(result.errors.isEmpty)
        XCTAssertEqual(result.warnings.count, 1)
        XCTAssertEqual(result.info.count, 1)
        XCTAssertNotNil(result.metrics)
        XCTAssertEqual(result.metrics?.fieldsMapped, 10)
    }
    
    func testFailedResult() {
        let error = TransformationError(
            code: "TRANSFORM_FAILED",
            message: "Transformation failed"
        )
        
        let result = TransformationResult<String>.failure(
            errors: [error],
            warnings: ["Warning"],
            info: ["Attempted transformation"]
        )
        
        XCTAssertFalse(result.success)
        XCTAssertNil(result.target)
        XCTAssertEqual(result.errors.count, 1)
        XCTAssertEqual(result.errors[0].code, "TRANSFORM_FAILED")
        XCTAssertEqual(result.warnings.count, 1)
        XCTAssertEqual(result.info.count, 1)
    }
    
    // MARK: - Metrics Tests
    
    func testTransformationMetrics() {
        let metrics = TransformationMetrics(
            duration: 1.5,
            fieldsMapped: 15,
            fieldsUnmapped: 3,
            dataLossCount: 1,
            memoryUsed: 1024
        )
        
        XCTAssertEqual(metrics.duration, 1.5)
        XCTAssertEqual(metrics.fieldsMapped, 15)
        XCTAssertEqual(metrics.fieldsUnmapped, 3)
        XCTAssertEqual(metrics.dataLossCount, 1)
        XCTAssertEqual(metrics.memoryUsed, 1024)
        
        // Data fidelity = 15 / (15 + 3) = 0.833...
        XCTAssertEqual(metrics.dataFidelity, 15.0 / 18.0, accuracy: 0.001)
    }
    
    func testDataFidelityCalculation() {
        // Perfect fidelity
        let perfect = TransformationMetrics(
            duration: 0.1,
            fieldsMapped: 10,
            fieldsUnmapped: 0,
            dataLossCount: 0
        )
        XCTAssertEqual(perfect.dataFidelity, 1.0)
        
        // 50% fidelity
        let half = TransformationMetrics(
            duration: 0.1,
            fieldsMapped: 5,
            fieldsUnmapped: 5,
            dataLossCount: 0
        )
        XCTAssertEqual(half.dataFidelity, 0.5)
        
        // No fields (edge case)
        let none = TransformationMetrics(
            duration: 0.1,
            fieldsMapped: 0,
            fieldsUnmapped: 0,
            dataLossCount: 0
        )
        XCTAssertEqual(none.dataFidelity, 1.0)  // Default to 1.0 when no fields
    }
    
    // MARK: - Metrics Builder Tests
    
    func testMetricsBuilder() async {
        let builder = TransformationMetricsBuilder()
        
        await builder.start()
        
        // Simulate some work
        try? await Task.sleep(nanoseconds: 100_000_000)  // 0.1 seconds
        
        await builder.recordMappedField()
        await builder.recordMappedField()
        await builder.recordMappedField()
        
        await builder.recordUnmappedField()
        
        await builder.recordDataLoss()
        
        let metrics = await builder.build()
        
        XCTAssertGreaterThan(metrics.duration, 0.0)
        XCTAssertEqual(metrics.fieldsMapped, 3)
        XCTAssertEqual(metrics.fieldsUnmapped, 1)
        XCTAssertEqual(metrics.dataLossCount, 1)
    }
    
    // MARK: - Integration Test Helpers
    
    func testSendableConformance() {
        // Ensure all types conform to Sendable for Swift 6 concurrency
        func checkSendable<T: Sendable>(_: T.Type) {}
        
        checkSendable(TransformationContext.self)
        checkSendable(TransformationConfiguration.self)
        checkSendable(TransformationRule.self)
        checkSendable(TransformationError.self)
        checkSendable(TransformationMetrics.self)
    }
}

// MARK: - Builder Tests

final class TransformationBuilderTests: XCTestCase {
    
    func testBasicBuilder() {
        let builder = TransformationBuilder()
        
        let rules = builder
            .map("PID-5")
            .to("patient.name")
            .describe("Patient name mapping")
            .build()
        
        XCTAssertEqual(rules.count, 1)
        XCTAssertEqual(rules[0].sourcePath, "PID-5")
        XCTAssertEqual(rules[0].targetPath, "patient.name")
        XCTAssertEqual(rules[0].description, "Patient name mapping")
        XCTAssertFalse(rules[0].required)
    }
    
    func testMultipleRules() {
        let builder = TransformationBuilder()
        
        let rules = builder
            .map("PID-5")
            .to("patient.name")
            .required()
            
            .map("PID-7")
            .to("patient.birthTime")
            
            .map("PID-8")
            .to("patient.gender")
            .required()
            
            .build()
        
        XCTAssertEqual(rules.count, 3)
        XCTAssertEqual(rules[0].sourcePath, "PID-5")
        XCTAssertTrue(rules[0].required)
        XCTAssertEqual(rules[1].sourcePath, "PID-7")
        XCTAssertFalse(rules[1].required)
        XCTAssertEqual(rules[2].sourcePath, "PID-8")
        XCTAssertTrue(rules[2].required)
    }
    
    func testBuilderWithTransformation() {
        let builder = TransformationBuilder()
        
        let rules = builder
            .map("PID-5")
            .to("patient.name")
            .transform(CommonTransformations.uppercase)
            .build()
        
        XCTAssertEqual(rules.count, 1)
        XCTAssertNotNil(rules[0].transform)
        
        let result = rules[0].transform?("john doe")
        XCTAssertEqual(result, "JOHN DOE")
    }
    
    func testCommonTransformations() {
        // Test uppercase
        XCTAssertEqual(CommonTransformations.uppercase("hello"), "HELLO")
        
        // Test lowercase
        XCTAssertEqual(CommonTransformations.lowercase("WORLD"), "world")
        
        // Test trim
        XCTAssertEqual(CommonTransformations.trim("  space  "), "space")
        
        // Test remove whitespace
        XCTAssertEqual(CommonTransformations.removeWhitespace("a b c"), "abc")
        
        // Test format phone
        XCTAssertEqual(CommonTransformations.formatPhone("5551234567"), "555-123-4567")
        
        // Test format date
        XCTAssertEqual(CommonTransformations.formatDate("20240101"), "2024-01-01")
        
        // Test v2 datetime to ISO
        XCTAssertEqual(CommonTransformations.v2DateTimeToISO("20240101120000"), "2024-01-01T12:00:00")
    }
    
    func testComponentExtraction() {
        let extract = CommonTransformations.component(1, separator: "^")
        XCTAssertEqual(extract("Smith^John^M"), "John")
        
        let extractFirst = CommonTransformations.component(0)
        XCTAssertEqual(extractFirst("Smith^John"), "Smith")
    }
    
    func testValueMapping() {
        let genderMap = CommonTransformations.mapValue([
            "M": "Male",
            "F": "Female"
        ], default: "Unknown")
        
        XCTAssertEqual(genderMap("M"), "Male")
        XCTAssertEqual(genderMap("F"), "Female")
        XCTAssertEqual(genderMap("X"), "Unknown")
    }
    
    func testTransformationTemplates() {
        // Test ADT patient demographics template
        let adtRules = TransformationTemplate.adtPatientDemographics
        XCTAssertGreaterThan(adtRules.count, 0)
        
        // Verify required fields
        let requiredRules = adtRules.filter { $0.required }
        XCTAssertGreaterThan(requiredRules.count, 0)
        
        // Test ORU observations template
        let oruRules = TransformationTemplate.oruObservations
        XCTAssertGreaterThan(oruRules.count, 0)
        
        // Test CDA to ADT template
        let cdaRules = TransformationTemplate.cdaToAdtPatientDemographics
        XCTAssertGreaterThan(cdaRules.count, 0)
    }
}
