# SwiftLint Configuration for HL7kit
# Swift 6.2 Best Practices and Coding Standards

# Paths to include/exclude from linting
included:
  - Sources
  - Tests

excluded:
  - .build
  - .swiftpm
  - docs
  - Examples

# Opt-in rules to enforce Swift 6.2 best practices
opt_in_rules:
  # Concurrency and Actor-related rules (Swift 6.2 focus)
  - strict_fileprivate
  - explicit_acl
  - explicit_top_level_acl
  
  # Code quality rules
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - empty_count
  - explicit_init
  - extension_access_modifier
  - fatal_error_message
  - file_header
  - first_where
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - nimble_operator
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - static_operator
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Disabled rules
disabled_rules:
  - todo # Allow TODO comments during development
  - line_length # Handled by custom configuration below

# Custom rule configurations

# Line length - allow slightly longer lines for HL7 message formatting
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

# File length - keep files focused and modular
file_length:
  warning: 400
  error: 500
  ignore_comment_only_lines: true

# Type body length - encourage smaller, focused types
type_body_length:
  warning: 250
  error: 350

# Function body length - keep functions focused
function_body_length:
  warning: 50
  error: 80

# Function parameter count - limit for better API design
function_parameter_count:
  warning: 5
  error: 8

# Cyclomatic complexity - maintain code simplicity
cyclomatic_complexity:
  warning: 10
  error: 15
  ignores_case_statements: true

# Nesting depth - avoid deeply nested code
nesting:
  type_level:
    warning: 2
    error: 3
  function_level:
    warning: 3
    error: 5

# Type name rules - PascalCase for types
type_name:
  min_length: 3
  max_length: 40
  excluded:
    - ID
    - HL7
    - MSH
    - PID
    - OBX
    - ADT
    - ACK
    - ORM
    - ORU
    - QRY
    - QBP
    - RIM
    - CDA
    - CX
    - CE
    - XPN
    - XAD
    - ST
    - TX
    - FT
    - NM
    - BL
    - INT
    - REAL
    - TS
    - II
    - URL
    - URI
    - API

# Identifier name rules - camelCase for identifiers
identifier_name:
  min_length: 2
  max_length: 40
  excluded:
    - id
    - ii
    - v2
    - v3
    - r4
    - r5
    - to
    - of
    - at
    - on
    - in
    - db
    - vm
    - io

# Large tuple rules - encourage using structs instead
large_tuple:
  warning: 3
  error: 4

# Force cast - discourage force casts
force_cast: warning

# Force try - discourage force try
force_try: warning

# Force unwrapping - discourage force unwrapping
force_unwrapping: warning

# Vertical whitespace - maintain readability
vertical_whitespace:
  max_empty_lines: 2

# Trailing whitespace
trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: false

# Colon spacing
colon:
  flexible_right_spacing: false
  apply_to_dictionaries: true

# Comma spacing
comma: warning

# Opening brace spacing
opening_brace: warning

# Statement position
statement_position:
  statement_mode: default

# Return arrow whitespace
return_arrow_whitespace: warning

# Operator function whitespace
operator_whitespace: warning

# Empty parameters
empty_parameters: warning

# Void return
void_return: warning

# Legacy constant/constructor
legacy_constant: warning
legacy_constructor: warning

# Shorthand operator
shorthand_operator: warning

# Syntactic sugar
syntactic_sugar: warning

# Mark - encourage MARK comments for organization
mark: warning

# Multiple closures with trailing closure
multiple_closures_with_trailing_closure: warning

# Redundant discardable let
redundant_discardable_let: warning

# Redundant optional initialization
redundant_optional_initialization: warning

# Redundant void return
redundant_void_return: warning

# Trailing comma - require trailing commas in arrays/dictionaries
trailing_comma:
  mandatory_comma: true

# Unused optional binding
unused_optional_binding:
  ignore_optional_try: false

# Custom rules for HL7-specific patterns
custom_rules:
  # HL7 message validation should use throws
  hl7_validation_throws:
    name: "HL7 Validation Throws"
    regex: 'func validate\(\)\s*(?!throws)'
    match_kinds:
      - keyword
    message: "Validation functions should throw errors"
    severity: warning

  # Encourage Sendable conformance for HL7 types
  hl7_sendable_protocol:
    name: "HL7 Sendable Protocol"
    regex: '(struct|class|enum)\s+\w+(Message|Resource|Segment|Field|Component)[^:]*:'
    match_kinds:
      - keyword
    message: "Consider making HL7 types conform to Sendable for Swift 6.2 concurrency"
    severity: warning

  # Encourage actor usage for shared state
  hl7_actor_usage:
    name: "HL7 Actor Usage"
    regex: 'class\s+\w+(Manager|Service|Handler|Processor)[^:]*:'
    match_kinds:
      - keyword
    message: "Consider using actor instead of class for shared state in Swift 6.2"
    severity: warning

  # Encourage async/await over completion handlers
  hl7_async_await:
    name: "HL7 Async/Await"
    regex: 'func\s+\w+.*completion:'
    match_kinds:
      - keyword
    message: "Consider using async/await instead of completion handlers in Swift 6.2"
    severity: warning

  # Discourage force unwrapping in production code (except tests)
  no_force_unwrap_production:
    name: "No Force Unwrap in Production"
    regex: '\!\s*(?!\/\/|$)'
    match_kinds: []
    message: "Avoid force unwrapping in production code"
    severity: warning
    excluded: ".*Tests\\.swift"

  # Require documentation for public APIs
  public_api_documentation:
    name: "Public API Documentation"
    regex: 'public\s+(func|var|let|struct|class|enum|protocol|actor|typealias)'
    match_kinds:
      - keyword
    message: "Public APIs should have documentation comments"
    severity: warning

# Reporter type
reporter: "github-actions-logging"

# Warnings as errors - enforce during development
# strict: false # Set to true in CI for stricter enforcement

# Baseline file for incremental improvements
# baseline: .swiftlint_baseline.json
